baseURL = ""
relativeURLs = "True"
languageCode = "en-us"
title = "Orel's Website"
theme = "risotto"

[params.theme]
palette = "base16-dark"

[[menu.main]]
identifier = "blog"
name = "blog"
title = "blog"
url = "/posts"

[[menu.main]]
identifier = "projects"
name = "projects"
title = "projects"
url = "/projects"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/orellazri"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/orellazri"
